#!/usr/bin/env bash
# Generates pkg/security/syscalls_<arch>.go, the name -> number tables the
# seccomp compiler resolves profiles against.
#
# Merges two sources, kernel headers winning: the uapi headers where installed,
# Go's zsysnum_linux_*.go as fallback. Neither alone is enough — Go's amd64
# table stops at 302 (about Linux 3.15) and so leaves out seccomp itself at 317,
# which gave us a runtime that couldn't install a filter at all on amd64.
#
# A missing name can't be allowed by a profile, which fails safe. A missing name
# the runtime needs to call is a real bug, hence the tests in pkg/security.
#
# Rerun after a toolchain or kernel-header upgrade.
set -euo pipefail

cd "$(dirname "$0")/.."
goroot="$(go env GOROOT)"
out_dir="pkg/security"

# arm64 uses the asm-generic numbering so the generic header is right for it.
# 32-bit arm has its own table and no generic equivalent, so it falls back to Go.
header_for() {
	case "$1" in
	amd64) echo "/usr/include/x86_64-linux-gnu/asm/unistd_64.h" ;;
	arm64) echo "/usr/include/asm-generic/unistd.h" ;;
	*) echo "" ;;
	esac
}

for arch in amd64 arm64 arm; do
	go_src="${goroot}/src/syscall/zsysnum_linux_${arch}.go"
	header="$(header_for "$arch")"
	out="${out_dir}/syscalls_${arch}.go"

	# Go's table first, header second, so the header's value wins on duplicates.
	pairs="$(mktemp)"
	trap 'rm -f "$pairs"' EXIT

	sources=""
	if [[ -f "$go_src" ]]; then
		grep -E '^\s+SYS_[A-Z0-9_]+\s+=\s+[0-9]+$' "$go_src" |
			sed -E 's/^[[:space:]]+SYS_([A-Z0-9_]+)[[:space:]]+=[[:space:]]+([0-9]+)$/\1 \2/' |
			tr '[:upper:]' '[:lower:]' >>"$pairs"
		sources="${go_src#"$goroot"/}"
	fi
	if [[ -n "$header" && -f "$header" ]]; then
		# Plain "#define __NR_name 123" only — the __NR3264_* aliases and
		# arithmetic forms aren't numbers and guessing would poison the table.
		grep -E '^#define __NR_[a-z0-9_]+ [0-9]+$' "$header" |
			sed -E 's/^#define __NR_([a-z0-9_]+) ([0-9]+)$/\1 \2/' >>"$pairs"
		sources="${sources:+$sources, }${header}"
	fi

	if [[ ! -s "$pairs" ]]; then
		echo "skipping ${arch}: no syscall source available" >&2
		rm -f "$pairs"
		continue
	fi

	{
		echo "// Code generated by hack/gen_syscalls.sh; DO NOT EDIT."
		echo "// Sources: ${sources}"
		echo
		echo "package security"
		echo
		echo "// syscallNumbers maps a seccomp profile syscall name to its number on"
		echo "// linux/${arch}. Names are as the OCI runtime-spec spells them: lowercase,"
		echo "// no SYS_ prefix."
		echo "var syscallNumbers = map[string]int{"
		# Last definition wins, then sort by number so the file reads sensibly.
		awk '{ n[$1] = $2 } END { for (k in n) print n[k], k }' "$pairs" |
			sort -n -k1 |
			while read -r num name; do
				printf '\t"%s": %s,\n' "$name" "$num"
			done
		echo "}"
	} >"$out"

	gofmt -w "$out"
	echo "generated ${out} ($(grep -cE '^[[:space:]]+"' "$out") syscalls) from ${sources}"
	rm -f "$pairs"
done
